name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - run: go version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Examine source code
        run: go vet -v ./...

      - name: Update Go report card
        uses: creekorful/goreportcard-action@v1.0
